In [20]:
import pandas as pd
import os
import re
import sklearn

In [21]:
df=pd.read_csv("BankNote_Authentication.csv")
df.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [22]:
df['class'].value_counts()

0    762
1    610
Name: class, dtype: int64

In [23]:
df.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [27]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]
X.shape, y.shape

((1372, 4), (1372,))

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(960, 4)
(412, 4)
(960,)
(412,)


In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [30]:
y_pred=classifier.predict(X_test)
y_pred

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,

In [31]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

In [32]:
score

0.9878640776699029

In [35]:
import pickle
pickle_out=open("classifier.pkl", "wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

In [38]:
fi = pd.DataFrame({'feature': list(X.columns),
                   'importance': classifier.feature_importances_}).\
                    sort_values('importance', ascending = False)

# Display
fi.head()

feature  importance
0  variance    0.555407
1  skewness    0.227724
2  curtosis    0.162263
3   entropy    0.054606

In [39]:
result=classifier.predict(X_test)
result

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,

In [40]:
result1=classifier.predict(X_test)[0]
result1

1

In [44]:
out=y_test.values
out[0]

1

In [45]:
type(y_test)

pandas.core.series.Series

In [46]:
type(out)

numpy.ndarray

In [49]:
rain_rf_probs = classifier.predict_proba(X_test)
rain_rf_probs[:2]

array([[0.02, 0.98],
       [1.  , 0.  ]])

In [50]:
type(rain_rf_probs)

numpy.ndarray

In [51]:
type(X_test)

pandas.core.frame.DataFrame

In [53]:
rain_rf_prob = classifier.predict_proba(X_test)[0]
rain_rf_prob

array([0.02, 0.98])

In [54]:
rain_rf_prob = classifier.predict_proba(X_test)[:]
rain_rf_prob

array([[0.02, 0.98],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.99, 0.01],
       [0.99, 0.01],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.96, 0.04],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.98, 0.02],
       [0.02, 0.98],
       [0.01, 0.99],
       [0.  , 1.  ],
       [0.98, 0.02],
       [1.  , 0.  ],
       [0.03, 0.97],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.99, 0.01],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.02, 0.98],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  ,

In [55]:
rain_rf_prob = classifier.predict_proba(X_test)[:,1]
rain_rf_prob

array([0.98, 0.  , 1.  , 0.01, 0.01, 0.  , 0.  , 0.04, 1.  , 1.  , 0.01,
       0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.98, 0.  , 0.  , 1.  , 0.  ,
       0.01, 1.  , 0.  , 0.99, 0.  , 0.99, 0.  , 0.  , 1.  , 0.02, 0.98,
       0.99, 1.  , 0.02, 0.  , 0.97, 0.75, 1.  , 0.01, 1.  , 0.  , 0.02,
       0.98, 1.  , 0.  , 0.  , 1.  , 0.  , 0.01, 0.99, 0.17, 1.  , 1.  ,
       0.  , 1.  , 1.  , 0.02, 1.  , 0.87, 0.01, 0.01, 0.  , 0.01, 1.  ,
       1.  , 1.  , 0.94, 0.  , 0.76, 0.  , 0.99, 0.01, 0.06, 1.  , 0.  ,
       0.01, 0.08, 0.  , 1.  , 1.  , 0.  , 0.  , 1.  , 1.  , 0.  , 0.  ,
       0.  , 0.01, 0.01, 1.  , 1.  , 0.98, 1.  , 0.01, 0.  , 0.  , 1.  ,
       1.  , 0.  , 1.  , 0.  , 0.01, 0.  , 1.  , 0.02, 1.  , 0.99, 1.  ,
       0.01, 1.  , 0.  , 0.05, 1.  , 0.02, 0.  , 0.  , 0.99, 0.99, 0.  ,
       0.  , 1.  , 1.  , 0.6 , 0.97, 0.92, 0.02, 0.72, 0.  , 0.  , 0.  ,
       0.01, 0.06, 0.01, 1.  , 0.  , 0.  , 0.01, 0.02, 1.  , 0.  , 1.  ,
       1.  , 0.02, 0.  , 0.88, 0.01, 0.  , 0.98, 0.